### ISSUE TITLE
Dependencies cannot be found

### ISSUE THREAD

**Issue by andruu** [ffMathy/FluffySpoon.JavaScript.InversionOfControl.Vue#2]
I keep on getting the following error when running `npm run serve` even though they are installed.

```
These dependencies were not found:

* @fluffy-spoon/inverse-vue in ./src/main.ts
* @fluffy-spoon/inverse in ./src/container.ts, ./src/services/AxiosHttpService.ts

To install them, you can run: npm install --save @fluffy-spoon/inverse-vue @fluffy-spoon/inverse

Version: typescript 3.3.3333, tslint 5.13.0
```

**Comment by ffMathy** [comment]
Weird. Can you upload a ZIP or make an example of the problem?

**Comment by ffMathy** [comment]
Closing until more information is provided.

**Comment by JornPalsenbarg** [comment]
@ffMathy I have the same problem. In browser i got a case-sensitive error. Renaming index.js, index.map.js and index.d.ts to Index.js, Index.map.js and Index.d.ts (capital I) fixed the problem.

**Comment by ffMathy** [comment]
This has been resolved.
